apiVersion: v1
kind: Service
metadata:
  name: "another-cloud-project-service"
  labels:
    {{- include "another-cloud-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "another-cloud-project.selectorLabels" . | nindent 4 }}
