name: Deployment Infrastructure
env:
  tf_actions_working_dir: infrastructure/

on:
  workflow_dispatch:
    inputs:
      deploy_infrastructure:
        description: 'Deploy Infrastructure'
        required: true
        type: string
        default: ''

jobs:
  infrastructure_deploy:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Check working directory
        run: pwd
      
      - name: Check files in working directory
        run: ls -la

      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.tf_actions_working_dir }}
    
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.tf_actions_working_dir }}
